### ISSUE TITLE
Wrong swagger Types/Formats for start and end time in TrackModel

### ISSUE THREAD

**Issue by ianmiddelkamp** [mycartracks/mycartracks#1]
swaggerTypes/Formats need to be 'double' or deserialization transforms timestamps into negative numbers.

**Comment by peok** [comment]
Hello Ian,
can you please send some example or code where it is used? Thank you.

**Comment by ianmiddelkamp** [comment]
Yes. 
Here is the generated swaggerTypes map for TrackModel.php 

`protected static $swaggerTypes = [
        'name' => 'string',
        'description' => 'string',
        'category' => 'string',
        'carId' => 'int',
        'userId' => 'int',
        'startTime' => 'int',
        'endTime' => 'int',
        'addressFrom' => 'string',
        'addressTo' => 'string',
        'id' => 'int',
        'device' => 'string',
        'totalDistance' => 'double',
        'totalTime' => 'int',
        'movingTime' => 'int',
        'maxSpeed' => 'double',
        'avgSpeed' => 'double',
        'avgMovingSpeed' => 'double',
        'minElevation' => 'double',
        'maxElevation' => 'double',
        'totalElevation' => 'double',
        'minGrade' => 'double',
        'maxGrade' => 'double',
        'created' => 'int',
        'updated' => 'int'
    ];`
Here is my code which grabs the tracks. 

`public function getTracksById($MyCarTracksId, $StartTime){
        $apiInstance = new MyCarTracks\Api\TracksApi(
            new GuzzleHttp\Client(),
            $this->CONFIG
        );
        $ReturnArray = array();
        $TracksPage = 0;
        do{
            $getTracksResult = $apiInstance->tracksGet($MyCarTracksId, null,null, null, null, null,  null,  null, $TracksPage, 1000);
            $Tracks = $getTracksResult->getData();
           
            $Timezone = new DateTimeZone("America/Toronto");
            foreach($Tracks as $TrackObject){
                //if moving time greater than 6000 milliseconds 
                if($TrackObject->getMovingTime() > 6000 && $TrackObject->getStartTime() > $StartTime){
                    $DTStart = new DateTime('@'.$TrackObject->getStartTime()/1000); 
                    $DTStart->setTimezone($Timezone);
                    $DTEnd = new DateTime('@'.$TrackObject->getEndTime()/1000); 
                    $DTEnd->setTimezone($Timezone);
                    $Track = array(        
                        'startTime' =>$DTStart->format('Y-m-d H:i:s'),
                        'endTime' => $DTEnd->format('Y-m-d H:i:s'),
                        'addressFrom' => $TrackObject->getAddressFrom(),
                        'addressTo' => $TrackObject->getAddressTo(),
                        'id' => $TrackObject->getId(),          
                        'totalDistance' => $TrackObject->getTotalDistance(),
                        'totalTime' => $TrackObject->getTotalTime(),
                        'movingTime' => $TrackObject->getMovingTime(),
                        'maxSpeed' => $TrackObject->getMaxSpeed(),
                        'avgSpeed' => $TrackObject->getAvgSpeed(),
                        'avgMovingSpeed' => $TrackObject->getAvgMovingSpeed(),
                        'TrackPoints'=>array()
                        );
                        $PointsPage = 0;
                        do{
                            $getTrackPointsResult = $apiInstance->trackpointsIdGet($TrackObject->getId(), null, null, null,  $PointsPage, 1000);
                            $TrackPoints =   $getTrackPointsResult->getData();
                            //var_dump();
                            foreach($TrackPoints as $TrackPoint){
                                $TrackPoint = array(        
                                    'id' => $TrackPoint->getId(),
                                    'lat' => $TrackPoint->getLatitude(),
                                    'lng' => $TrackPoint->getLongitude(),
                                    'altitude' => $TrackPoint->getAltitude(),
                                    'time' => $TrackPoint->getTime(),
                                    'speed' => $TrackPoint->getSpeed(),
                                    'accuracy' => $TrackPoint->getAccuracy()
                                );
                                $Track['TrackPoints'][] = $TrackPoint;
                                //var_dump($TrackPoint);
                                $PointsPage++;
                            }
                        }while($getTrackPointsResult->getHasMore());
                    
                        $ReturnArray[]  = $Track;
                }
                
            }
            $TracksPage++;
        }while($getTracksResult->getHasMore());
  
     
       $this->RESPONSE{'results'} =  $ReturnArray;
       
        $this->RESPONSE{'success'} = true;
        return $this->RESPONSE;
    }`

I was getting negative numbers - something like '-2015XXXXXX' - when calling $TrackObject->getStartTime(), and $TrackObject->getEndTime(). My fix for this was changing the swaggerType and swaggerFormat maps in TrackModel.php, setting the values for keys startTime and endTime to double. Please let me know if I am doing something wrong which is creating this issue.

Also I am new to github, and if I am breaking etiquette, please feel free to school me.

**Comment by peok** [comment]
Hello Ian,
this seems like an issue with PHP and the fact that integer in PHP is platform dependent which in most cases is 32-bit. startTime and endTime is a 64-bit long number.

From documentation:
> The size of an integer is platform-dependent, although a maximum value of about two billion is the usual value (that's 32 bits signed). 64-bit platforms usually have a maximum value of about 9E18, except on Windows prior to PHP 7, where it was always 32 bit. PHP does not support unsigned integers. Integer size can be determined using the constant PHP_INT_SIZE, maximum value using the constant PHP_INT_MAX since PHP 5.0.5, and minimum value using the constant PHP_INT_MIN since PHP 7.0.0.

If you have PHP 7+ try to adjust the configs or try the code on a 64-bit platform. Check also this [https://stackoverflow.com/questions/864058/how-to-have-64-bit-integer-on-php](https://stackoverflow.com/questions/864058/how-to-have-64-bit-integer-on-php)

**Comment by ianmiddelkamp** [comment]
Thank you very much
